[PARSER]
    Name        json
    Format      json

[PARSER]
    Name        nginx_error
    Format      regex
    Regex       ^(?<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?<level>[^\]]+)\] (?<pid>\d+)#(?<tid>\d+): \*(?<connection>\d+) (?<message>.*)$
    Time_Key    time
    Time_Format %Y/%m/%d %H:%M:%S
