[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name                tail
    Path                C:/Projects/2026_kw_capstone_project/dev_tools/parsed_logs/test_sample
    Tag                 security.log
    Refresh_Interval    1
    Read_from_Head      True
    Parser              json

[OUTPUT]
    Name        stdout
    Match       *

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     localhost:9092
    Topics      log-topic
    Format      json
