spring:
  session:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3306/security_db?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true > 2
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-group
      auto-offset-reset: earliest     # 컨슈머가 처음 연결됐을 때, 이전에 쌓여있던 데이터가 있다면 처음부터 다 읽어오겠다는 뜻
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# 이 스프링 프로젝트가 실행될 때 사용하는 포트번호. 웹 브라우저에서 localhost:8080으로 접속하게됨.
server:
  port: 8080